name: xenium_5k_venv
channels:
  - conda-forge
  - bioconda
  - pkgs/r
  - defaults
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - pandas[excel]
  - pytorch
  - scanpy[leiden]
  - spatialdata
  - spatialdata-io
  - squidpy
  - seaborn
  - zarr
  - pydantic
  - mkdocs==1.6.1
  - mkdocs-include-markdown-plugin==7.1.5
  - mkdocs-jupyter==0.25.1
  - mkdocs-exclude==1.0.2
  - mkdocs-material==9.6.12
  - python-markdown-math==0.9
  - ruff
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mock
  - pip-tools
  - geosketch
  - scvi-tools
  - pip
  - pip:
      - git+https://github.com/deto/scTransformPy.git
